//
//  SearchViewController.swift
//  CoBook
//
//  Created protas on 6/5/20.
//  Copyright © 2020 CoBook. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class SearchViewController: BaseViewController {

    @IBOutlet var tableView: UITableView!

    var presenter: SearchPresenter

    // MARK: - Initializers

	init(presenter: SearchPresenter) {
        self.presenter = presenter
        super.init(nibName: "SearchViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    // MARK: - Life Cycle

	override func viewDidLoad() {
        super.viewDidLoad()
        presenter.view = self
        presenter.setup()
    }

    deinit {
        presenter.view = nil
    }
    

}

// MARK: - Privates

private extension SearchViewController {

    func setupLayout() {
        self.navigationItem.title = "Пошук всякої лупини"
    }

}

// MARK: - SearchView

extension SearchViewController: SearchView {

    func reload() {
        tableView.reloadData()
    }

    func set(dataSource: DataSource<SearchCellsConfigurator>?) {
        dataSource?.connect(to: tableView)
    }

    
}
