//
//  SignUpViewController.swift
//  CoBook
//
//  Created protas on 2/13/20.
//  Copyright © 2020 CoBook. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class SignUpViewController: UIViewController, SignUpViewProtocol {

	var presenter: SignUpPresenterProtocol = SignUpPresenter()

	override func viewDidLoad() {
        super.viewDidLoad()

        presenter.view = self
    }

}
