//
//  SignUpPresenter.swift
//  CoBook
//
//  Created protas on 2/13/20.
//  Copyright © 2020 CoBook. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol SignUpViewProtocol: class {

}

// MARK: Presenter -
protocol SignUpPresenterProtocol: class {
	var view: SignUpViewProtocol? { get set }
    func setup()
}

class SignUpPresenter: SignUpPresenterProtocol {

    weak var view: SignUpViewProtocol?

    func setup() {

    }
}
